### ISSUE TITLE
erro 404 ao tentar acessar o sistema pelo meu servidor PHP localhost:8000

### ISSUE THREAD

**Issue by thallys97** [Cyber-Root0/siga-api#2]
no google chrome, ao subir o servidor PHP local na pasta raiz "siga-api", usando a instrução: "php -S localhost:8000", recebo o seguinte erro: "The requested resource / was not found on this server."

**Comment by Cyber-Root0** [comment]
Olá! Boa noite @thallys97  validei  o erro, e enviei uma correção. Atualize o repositório, acesse o diretório raiz do projeto e execute o server php com o seguinte comando: php -S localhost:80 -t public public/index.php

Fico a disposição para eventuais dúvidas!  Grato. 


Bruno Alves
-------------------
